# Generated by Django 3.0.8 on 2020-07-20 18:35

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=48, verbose_name='دسته بندی')),
                ('cat_slug', models.SlugField(verbose_name='لینک دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_title', models.CharField(max_length=48, verbose_name='امکانات')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد آگهی')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان آگهی')),
                ('body', models.TextField(verbose_name='توضیحات')),
                ('price1', models.DecimalField(decimal_places=3, max_digits=17, verbose_name='ارزش کل ملک')),
                ('price2', models.DecimalField(decimal_places=3, max_digits=17, verbose_name='قیمت اجاره شنبه تا چهارشنبه')),
                ('price3', models.DecimalField(decimal_places=3, max_digits=17, verbose_name='قیمت اجاره چهارشنبه تا شنبه')),
                ('image', models.ImageField(upload_to='adspic', verbose_name='تصویر کاور')),
                ('image2', models.ImageField(upload_to='adspic', verbose_name='تصویر')),
                ('size1', models.IntegerField(verbose_name='متراژ زمین')),
                ('size2', models.IntegerField(verbose_name='متراژ بنا')),
                ('status', models.CharField(choices=[('R', 'اجاره شده'), ('N', 'خالی شده')], max_length=1, verbose_name='وضعیت فعلی')),
                ('category', models.OneToOneField(on_delete=builtins.any, to='Ads.category', verbose_name='دسته بندی')),
                ('services', models.ManyToManyField(to='Ads.service', verbose_name='امکانات')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
            },
        ),
    ]
