# Generated by Django 3.0.8 on 2020-07-21 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ads',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=17, verbose_name='قیمت اجاره شنبه تا چهارشنبه'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=17, verbose_name='قیمت اجاره چهارشنبه تا شنبه'),
        ),
    ]
